# # certificate.yaml
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: www
# spec:
#   secretName: www-tls
#   privateKey:
#     rotationPolicy: Always
#   commonName: www.door-store-moldova.pp.ua
#   dnsNames:
#     - www.door-store-moldova.pp.ua
#   usages:
#     - digital signature
#     - key encipherment
#     - server auth
#   issuerRef:
#     name: selfsigned
#     kind: ClusterIssuer
