apiVersion: v1
kind: Service
metadata:
  labels:
    run: frontend
  name: frontend-service
  namespace: illuminati
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{.Values.containerPort}}
  selector:
    run: frontend
  type: ClusterIP
